In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("Combined_Dataset.csv")

In [6]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [7]:
df.shape

(1000, 24)

In [8]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [9]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [11]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [13]:
df_clean = df.copy()

In [14]:
df_clean.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [15]:
df_clean["discount"] = df_clean["discount"].fillna(df_clean["discount"].mean())

In [16]:
df_clean.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                    0
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [17]:
df_clean["what_customer_said"] = df_clean["what_customer_said"].fillna("No review")

KeyError: 'what_customer_said'

In [18]:
df_clean["what_customers_said"] = df_clean["what_customers_said"].fillna("No Reviews")

In [19]:
df_clean.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                    0
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said         0
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [20]:
df_clean["seller_name"] = df_clean["seller_name"].fillna("Unknown")
df_clean["videos"] = df_clean["videos"].fillna("No Video")
df_clean["seller_information"] = df_clean["seller_information"].fillna("Not Available")
df_clean["variations"] = df_clean["variations"].fillna("No Variation")

In [21]:
df_clean.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [22]:
df_clean.duplicated.sum()

AttributeError: 'function' object has no attribute 'sum'

In [23]:
df_clean.duplicated().sum()

np.int64(0)

In [24]:
df_clean.drop_duplicates(inplace=True)

In [25]:
df_clean[["title","rating","initial_price"]].head()

            title  rating  initial_price
0     Lino Perros     3.8           3995
1  Tommy Hilfiger     4.5           2899
2           Lavie     4.4           2999
3          F Gear     4.4           1675
4       MYTRIDENT     4.7           2899

In [26]:
df_clean[df_clean["rating"] > 4.5]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.000000,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Video,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.000000,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,Unknown,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",No Video,Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
22,21427828,London Rag,Women Stiletto Heeled High-Top Boots,5.0,4,9599,60.000000,"""₹3,839.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,VOL███FAS███N P█████████,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...",No Video,SAI███USE███OT █████████ NA███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",boots
32,18656766,VStar,Beige Solid T-Shirt Bra,4.6,5,345,53.503982,"""₹345.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,V S███ CR███ION█████████,"[{""size"":""30B"",""value"":""31.5in"",""value_name"":""...",No Video,VI/███ AB███ ST█████████ODE███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
38,21873792,KARATCART,Cubic Zirconia Silver-Plated Wraparound Bracelet,4.6,5,3397,76.000000,"""₹815.00""",INR,http://assets.myntassets.com/assets/images/218...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Reviews,KOK███V G███AL █████████,"[{""size"":""Onesize"",""value"":""8.26in"",""value_nam...",No Video,Sho███58-███Sec█████████ain███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bracelet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,20085320,BULLMER,Men Pack of 2 Navy Blue & Turquoise Blue Long ...,4.8,12,3998,80.000000,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,Bod███ove███par█████████,"[{""size"":""M"",""value"":""39.0in"",""value_name"":""Ch...",No Video,Bod███ove███par█████████ No███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
968,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599,58.000000,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MAD███R P███T P█████████MIT███,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",No Video,621███ 6n███ kh█████████zia███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
986,17697474,Timex,Women White Dial & Gold Toned Analogue Watch T...,4.9,8,1995,20.000000,"""₹1,596.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,TIM███T R███IL █████████RIV████████████,"[{""size"":""Onesize""}]",No Video,"Fla███o. ███, 6█████████y C███████████████████...",No Variation,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.000000,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Reviews,Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...",No Variation,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.000000,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,Unknown,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Not Available,No Variation,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches

In [27]:
df_clean["discount_amount"] = (
    df_clean["initial_price"] * df_clean["discount"] / 100
)

In [28]:
df_clean[["initial_price","discount","discount_amount"]].head()

   initial_price  discount  discount_amount
0           3995      58.0          2317.10
1           2899      35.0          1014.65
2           2999      65.0          1949.35
3           1675      52.0           871.00
4           2899      17.0           492.83

In [29]:
df_clean.to_csv("cleaned_ecommerce_dataset.csv", index=False)

In [30]:
import os
os.listdir()

['-1.14-windows.xml',
 '.cache',
 '.copilot',
 '.gitconfig',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.m2',
 '.python_history',
 '.vscode',
 '.vscode-shared',
 'AppData',
 'Application Data',
 'archive.zip',
 'Assignment.ipynb',
 'cleaned_ecommerce_dataset.csv',
 'Combined_dataset.csv',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'Favorites',
 'hackathon',
 'HireMind-AI',
 'IdeaProjects',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'my_java_project',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{f17fec49-1142-11f0-af29-d1e849c228d9}.TM.blf',
 'NTUSER.DAT{f17fec49-1142-11f0-af29-d1e849c228d9}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{f17fec49-1142-11f0-af29-d1e849c228d9}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Videos']